In [59]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [60]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [61]:
x= dataset.drop(columns=['User ID', 'Purchased','Gender'])
y= dataset['Purchased']

In [62]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [63]:
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

# Linear

In [64]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear' )
classifier.fit(X_train, y_train)


SVC(kernel='linear')

In [65]:
y_pred = classifier.predict(X_test)

In [66]:
from sklearn.metrics import confusion_matrix ,accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[72,  1],
       [17, 30]])

# Non_Linear

In [68]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

classifier_poly = SVC(kernel = 'poly', random_state = 0)
classifier_poly.fit(X_train, y_train)

classifier_sigmoid = SVC(kernel = 'sigmoid', random_state = 0)
classifier_sigmoid.fit(X_train, y_train)


y_pred = classifier.predict(X_test)
y_pred_poly = classifier_poly.predict(X_test)
y_pred_sigmoid = classifier_sigmoid.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
cm_poly = confusion_matrix(y_test, y_pred_poly)
cm_sigmoid = confusion_matrix(y_test, y_pred_sigmoid)


print('The confusion_matrix for rbf\n',cm)
print('The confusion_matrix for poly\n',cm_poly)
print('The confusion_matrix for sigmoid\n',cm_sigmoid)

The confusion_matrix for rbf
 [[72  7]
 [ 4 37]]
The confusion_matrix for poly
 [[77  2]
 [17 24]]
The confusion_matrix for sigmoid
 [[65 14]
 [17 24]]
